### ISSUE TITLE
Add screenshot / preview to README

### ISSUE THREAD

**Issue by alexanderadam** [xplosionmind/joplin-theme#1]
It would be nice if others could see how it looks like before they're trying it. :wink:

**Comment by xplosionmind** [comment]
You’re absolutely right. I’ll wait for the app redesign (which I understand is happening in the next release) to fix possible display issues, and then I’ll add the screenshot for the updated css files.

Thanks!

**Comment by xplosionmind** [comment]
I added sample screenshots. You can check them out [here](https://github.com/xplosionmind/joplin-theme#screenshots)
